### ISSUE TITLE
python代码错误

### ISSUE THREAD

**Issue by leijdjcn** [foryichuanqi/Paper2022.09-Remaining-useful-life-prediction-by-TaFCN#3]
Traceback (most recent call last):
  File "D:\Download files\wenxiandaima\FCN\code\grid_FD_multi_channel_one_FCN_RUL_A2_attention_1out_all_train_for_test.py", line 431, in <module>
    plot_model(model, to_file=last_path+r"\Flatten.png", show_shapes=True)#########to_file='Flatten.png',last_path+r"\model\FCN_RUL_1out_train_valid_test\{}.h5
  File "C:\Users\Liyanhui\.conda\envs\tensor\lib\site-packages\keras\utils\vis_utils.py", line 421, in plot_model
    dot = model_to_dot(
  File "C:\Users\Liyanhui\.conda\envs\tensor\lib\site-packages\keras\utils\vis_utils.py", line 151, in model_to_dot
    if not check_pydot():
  File "C:\Users\Liyanhui\.conda\envs\tensor\lib\site-packages\keras\utils\vis_utils.py", line 53, in check_pydot
    except (OSError, pydot.InvocationException):
AttributeError: module 'pydot' has no attribute 'InvocationException

How to solve the above situation？

**Comment by foryichuanqi** [comment]
I suggest that you don't use the model I gave you, and use my code to train a new model for interpretability analysis.细微的环境变化都会造成模型无法使用，我建议你不要使用我给的模型，而是用我的代码训练一个新模型，用于可解释性分析。
